---
apiVersion: v1
kind: Pod
metadata:
  name: app-readinessprob
spec:
  containers:
  - name: app
    image: gcr.io/k8s-k3s/demo:v1.0.0
    ports:
    - name: http
      containerPort: 8000
    readinessProbe:
      httpGet:
        path: /ready
        port: http
      initialDelaySeconds: 10
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 3
