---
apiVersion: v1
kind: Pod
metadata:
  name: app-livenessprob
spec:
  containers:
  - name: app
    image: gcr.io/k8s-k3s/demo:v1.0.0
    ports:
    - name: http
      containerPort: 8000
    livenessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 15
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
